<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?php isset($title) && print($title); ?></title>
		<meta name="description" content="desafio-feng">

		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

		<!-- Custom styles for this template -->
		<link href="<?= $this->assets('css', 'main.css') ?>" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<main role="main" class="container">
			<?= $this->content() ?>
		</main>

		<footer class="text-muted">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
					</div>
					<div class="col-md-8">
					</div>
				</div>
			</div>
		</footer>

		<!-- Assets -->
		<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
		<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

		<script type="text/javascript" src="<?= $this->assets('js', 'main.js') ?>" ></script>
	</body>
</html>
