<?php
	$this->set('title', 'Desafio FENG');
	$this->wrapper('_wrapper');
?>
<style>
	.jumbotron {
		background-color: #fff;
	}
</style>
<section class="jumbotron text-center">
	<div class="container">
		<h1 class="jumbotron-heading"> Desafio FENG </h1>
		<p class="lead text-muted">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hunc vos beatum; Sed haec omittamus; Pauca mutat vel plura sane; Vide, quaeso, rectumne sit. Octavio fuit, cum illam severitatem in eo filio adhibuit, quem in adoptionem D. Et nemo nimium beatus est;
		</p>
		<p>
			<a href="<?= $this->url('/administration') ?>" class="btn btn-primary my-2"> Área de Administração </a>
		</p>
	</div>
</section>
