<?php
	$this->set('title','404: Not Found');
	$this->wrapper('_wrapper');
?>
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<h1> 404: Page Not Found</h1>
			<p>
				A página que você está procurando não foi encontrada. Verifique a barra de endereço
			</p>
			<p>
				<a href="<?= $this->url() ?>" class="btn btn-ls btn-info">Retornar ao site</a> 
			</p>
		</div>
	</div>
</div>
